Aligns with stack major and minor version, 8.16.0 release.
elastic/logstash-filter-elastic_integration pull request #210
Opened 2024-12-18 20:59 UTC by mashhurs

Prepares 8.16.0 plugin release.

2025-01-07 16:45 UTC, yaauie requested changes

2025-01-07 16:45 UTC, yaauie commented on CHANGELOG.md
> +  - Compatible with Logstash and Elasticsearch 8.16 versions
"Compatible with" is a bit overloaded, consider breaking it out:

```suggestion
  - Embeds Ingest Node components from Elasticsearch 8.16
  - Compatible with Logstash 8.x
```

2025-01-07 17:26 UTC, mashhurs commented on CHANGELOG.md
> +  - Compatible with Logstash and Elasticsearch 8.16 versions
Hm., compatibility across Logstash 8.x will be difficult since <=LS 8.14 version _embedded_ JDKs do not satisfy the requirement. WDYT if we change the statement to `Compatible with Logstash 8.15+`? Or `Compatible with Logstash 8.x as long as JDK requirement meets, 8.16 is recommended`.

2025-01-07 20:42 UTC, yaauie commented on CHANGELOG.md
> +  - Compatible with Logstash and Elasticsearch 8.16 versions
```suggestion
  - Embeds Ingest Node components from Elasticsearch 8.16
  - Compatible with Logstash 8.15+
```

2025-01-07 20:50 UTC, donoghuc approved these changes
LGTM with suggestion committed :)

2025-01-07 21:06 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/logstash-filter-elastic-integration-pull-request/builds/474)
* Commit: fafb928c22fc26a2a6cf0bebd1951b584510d814

### History
* :yellow_heart: [Build #470](https://buildkite.com/elastic/logstash-filter-elastic-integration-pull-request/builds/470) was flaky b319706039b436b8da004a8bc38c7cfb12c98092

<!--buildkite-pr-comment-logstash-filter-elastic-integration-pull-request
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/logstash-filter-elastic-integration-pull-request/builds/474","number":474,"commit":"fafb928c22fc26a2a6cf0bebd1951b584510d814"},{"buildStatus":{"state":"passed","success":true,"hasRetries":true,"hasNonPreemptionRetries":true},"url":"https://buildkite.com/elastic/logstash-filter-elastic-integration-pull-request/builds/470","number":470,"commit":"b319706039b436b8da004a8bc38c7cfb12c98092"}],"number":474}
buildkite-pr-comment-->

2025-01-07 21:14 UTC, yaauie approved these changes

2025-01-07 23:27 UTC, merged

2025-01-27 21:52 UTC, mashhurs commented
@logstashmachine backport 8.x