Add prerequisites doc section.
elastic/logstash-filter-elastic_integration pull request #211
Opened 2024-12-19 17:43 UTC by mashhurs

### Description
This change adds a prerequisites doc section to list up its requirements/expectations.

2025-01-07 17:07 UTC, yaauie requested changes

2025-01-07 17:07 UTC, yaauie commented on docs/index.asciidoc
> +- When upgrading the stack product(s) or plugin, make sure {es} and {kib} are upgraded to the target version before {ls} and <<plugins-{type}s-{plugin}>> plugin.
Guidance needs _inversion_.

 - Given:
   - Agent deploys pipelines based on Kibana version
   - Upgrading Kibana before this plugin will cause Agent to deploy pipelines that this plugin cannot handle.
 - Therefore: this plugin must be upgraded _before_ Kibana.


```suggestion
- This plugin embeds portions of Elasticsearch Ingest Node whose version matches the `major`.`minor` version of the plugin.
- When upgrading the {stack} product(s), this plugin should be upgraded _before_ {kib} to ensure that {agent}-managed pipelines have access to the expected functionality.
```

We also do _not_ need to major/minor align with Logstash, so long as the JDK requirements are met. This plugin can be upgraded independently of Logstash.

2025-01-07 17:07 UTC, yaauie commented on docs/index.asciidoc
> +- This plugin requires minimum Java 17 with its `8.series` versions and Java 21 with its `9.series` versions.
```suggestion
- This plugin requires minimum Java 17 with its `8.x` versions and Java 21 with its `9.x` versions.
```

2025-01-07 18:08 UTC, mashhurs commented on docs/index.asciidoc
> +- When upgrading the stack product(s) or plugin, make sure {es} and {kib} are upgraded to the target version before {ls} and <<plugins-{type}s-{plugin}>> plugin.
Good catch of `this plugin should be upgraded _before_ {kib}`, thank you!

2025-01-07 18:29 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/logstash-filter-elastic-integration-pull-request/builds/473)
* Commit: 54604ad7392b497bd1cac8c769c5eceb49873ef9

### History
* :green_heart: [Build #471](https://buildkite.com/elastic/logstash-filter-elastic-integration-pull-request/builds/471) succeeded 813b6fd5c100447ba6ebb1e6cb7e1970055d662e

<!--buildkite-pr-comment-logstash-filter-elastic-integration-pull-request
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/logstash-filter-elastic-integration-pull-request/builds/473","number":473,"commit":"54604ad7392b497bd1cac8c769c5eceb49873ef9"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/logstash-filter-elastic-integration-pull-request/builds/471","number":471,"commit":"813b6fd5c100447ba6ebb1e6cb7e1970055d662e"}],"number":473}
buildkite-pr-comment-->

2025-01-07 20:41 UTC, yaauie approved these changes

2025-01-07 22:37 UTC, robbavey commented on docs/index.asciidoc
> +- This plugin requires minimum Java 17 with its `8.x` versions and Java 21 with its `9.x` versions.
```suggestion
[id="plugins-{type}s-{plugin}-prerequisites"]
===== Prerequisites
- This plugin embeds functionality from the version of {es} Ingest Node matching the `major`.`minor` version of this plugin.
- When upgrading the {stack}, ensure that this plugin is upgraded _before_ upgrading {kib} to ensure the best experience with {agent}-managed pipelines. 
- This plugin requires {ls} to run with a minimum of Java 17 with its `8.x` versions and Java 21 with its `9.x` versions.
```

Some wording suggestions: 
* Replaces Elasticsearch with {es}
* An attempt to clarify upgrade clause. I suspect @karenzone might have something better here
* Clarify that *Logstash* needs to run a minimum of Java 17

2025-01-07 22:43 UTC, karenzone commented on docs/index.asciidoc
> +- This plugin requires minimum Java 17 with its `8.x` versions and Java 21 with its `9.x` versions.
@mashhurs, do you want to take these changes and let me pick up again from there?

2025-01-07 22:52 UTC, mashhurs commented on docs/index.asciidoc
> +- This plugin requires minimum Java 17 with its `8.x` versions and Java 21 with its `9.x` versions.
@karenzone if you can please add/udpate on top of Rob's change, I will push the final one and merge. Thank you!

2025-01-08 00:33 UTC, karenzone commented on docs/index.asciidoc
> +- This plugin requires minimum Java 17 with its `8.x` versions and Java 21 with its `9.x` versions.
If we arrive on something different we want to try, I can add it as a suggestion.  While we're deciding, I'm pasting what I have here so that I don't lose it: 

[id="plugins-{type}s-{plugin}-requirements"]
===== Upgrade tips and requirements

- When you upgrade the {stack}, upgrade {ls} (or this plugin specifically) _before_ you upgrade {kib}.
  (Note that this requirement is a departure from the typical {stack} https://www.elastic.co/guide/en/elastic-stack/current/installing-elastic-stack.html#install-order-elastic-stack[installation order].) 
+
The {es}-{ls}-{kib} installation order embeds functionality from a version of {es} Ingest Node that is compatible with this plugin, and ensures the best experience with {agent}-managed pipelines. 

- This plugin requires Java 17 minimum with {ls} `8.x` versions and Java 21 minimum with {ls} `9.x` versions.

2025-01-08 00:50 UTC, karenzone commented on docs/index.asciidoc
> +- This plugin requires minimum Java 17 with its `8.x` versions and Java 21 with its `9.x` versions.
```suggestion
[id="plugins-{type}s-{plugin}-requirements"]
===== Requirements and upgrade guidance

- This plugin requires Java 17 minimum with {ls} `8.x` versions and Java 21 minimum with {ls} `9.x` versions.
- When you upgrade the {stack}, upgrade {ls} (or this plugin specifically) _before_ you upgrade {kib}.
  (Note that this requirement is a departure from the typical {stack} https://www.elastic.co/guide/en/elastic-stack/current/installing-elastic-stack.html#install-order-elastic-stack[installation order].) 
+
The {es}-{ls}-{kib} installation order ensures the best experience with {agent}-managed pipelines, and embeds functionality from a version of {es} Ingest Node that is compatible with the plugin version (`major`.`minor`).   
```

2025-01-08 00:52 UTC, karenzone commented on docs/index.asciidoc
> +- This plugin requires minimum Java 17 with its `8.x` versions and Java 21 with its `9.x` versions.
Renders like this: 
<img width="923" alt="Screenshot 2025-01-07 at 7 51 08 PM" src="https://github.com/user-attachments/assets/dbf74f9c-b4cc-4021-b678-3f7d5fc2e5c6" />

Please free to tweak as you see fit... as long as you don't break anything.  :-D

2025-01-08 01:01 UTC, robbavey approved these changes
LGTM

2025-01-08 01:10 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/logstash-filter-elastic-integration-pull-request/builds/476)
* Commit: a7c484da9b723ea4e8ffb3e00cf5bb0a25587345

### History
* :green_heart: [Build #473](https://buildkite.com/elastic/logstash-filter-elastic-integration-pull-request/builds/473) succeeded 54604ad7392b497bd1cac8c769c5eceb49873ef9
* :green_heart: [Build #471](https://buildkite.com/elastic/logstash-filter-elastic-integration-pull-request/builds/471) succeeded 813b6fd5c100447ba6ebb1e6cb7e1970055d662e

<!--buildkite-pr-comment-logstash-filter-elastic-integration-pull-request
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/logstash-filter-elastic-integration-pull-request/builds/476","number":476,"commit":"a7c484da9b723ea4e8ffb3e00cf5bb0a25587345"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/logstash-filter-elastic-integration-pull-request/builds/473","number":473,"commit":"54604ad7392b497bd1cac8c769c5eceb49873ef9"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/logstash-filter-elastic-integration-pull-request/builds/471","number":471,"commit":"813b6fd5c100447ba6ebb1e6cb7e1970055d662e"}],"number":476}
buildkite-pr-comment-->

2025-01-08 01:11 UTC, merged

2025-01-08 01:11 UTC, mashhurs commented
@logstashmachine backport 8.x

2025-01-08 01:12 UTC, mashhurs commented
@logstashmachine backport 8.16

2025-01-08 01:14 UTC, mashhurs commented
@logstashmachine backport 8.17